### ISSUE TITLE
Error "Incompatible API version (3.0)"

### ISSUE THREAD

**Issue by leonjalfon1** [cschleiden/vsts-quick-decompose#10]
I am trying to install the extension in TFS 2015.3 and I am getting the error "Incompatible API version (3.0)"
Maybe I downloaded the extension for TFS 2017?
where can I download the extension for TFS 2015.3?

Thanks

**Comment by cschleiden** [comment]
@leonjalfon1 That is by design, the extension relies on APIs that were only introduced with the API version 3.0.
