### ISSUE TITLE
Decompose returns a blank form

### ISSUE THREAD

**Issue by wjvanwyk** [cschleiden/vsts-quick-decompose#16]
When right-clicking on Decompose Work Item, it only returns a blank window with none of the expected functionality. Any changes or issues to be aware of that might have caused this?

![image](https://user-images.githubusercontent.com/3462813/30802815-9ee81d0a-a1df-11e7-85a6-b79d9d070612.png)

**Comment by cschleiden** [comment]
@wjvanwyk  Thanks a lot for reporting this, it's happening due to a product change on the VSTS accounts where the latest release is rolled out. I'll follow up and prepare a fix.

**Comment by cschleiden** [comment]
@wjvanwyk It should be fixed now, again, thanks for letting me know!
