### ISSUE TITLE
Area/Iteration values lost - ruins value of the plugin

### ISSUE THREAD

**Issue by Russweb** [cschleiden/vsts-quick-decompose#23]
Its missing something pretty critical, but easy to add, though.
When the work items are created, they are all set at the root path for iteration path and area path.
They do not keep the context/values of the parent item you were decomposing from. 
This causes the items to disappear, if you are in a team screen.
This forces the user to have to go find the items and set the values properly in order for them to return back to the team backlog. That negates a lot of the benefit.
Fix that, and I can update this to 5 stars.!

**Comment by cschleiden** [comment]
That should work, if it doesn't, then that's a bug. 

All of the children will get the iteration/area path of the decomposed parent. This is not what you're seeing?

If you look at the REST API call in the network tools to create the work item, do you see the correct area/iteration path being passed to the API?

**Comment by Russweb** [comment]
I believe I found the problem. And yes, there is not a bug.
When in backlog view for a team, with Parents turned on, I started the Decompose from a higher level parent that is NOT in the team backlog.    Thanks for your rapid response.

Another thought.....
After a row is started to make a work item (like a story level), there can be a few different work item types. Unfortunately, VSTS does not have its "default work item" functionality working, and the wrong one is always there first, requiring the user to leave the keyboard, goto the mouse and click through the item types until they get to "story".  Is there a keyboard method you could use to allow that selection capability instead?

Thx!

**Comment by cschleiden** [comment]
Yep, it's Alt+Enter. Should say so in a tooltip I think.
