### ISSUE TITLE
On premises

### ISSUE THREAD

**Issue by brettjacobson** [cschleiden/vsts-quick-decompose#3]
Do you have plans to make it work with on premises TFS?  are there any reasons why it cannot work?

**Comment by cschleiden** [comment]
I _do_ have plans to support on prem, but the extension relies on a new REST API to get the work item types per level (from the process configuration) and that API will probably only be in the next major version of TFS, so I'm dependent on that.

**Comment by brettjacobson** [comment]
Thank you very much for the update!  We currently use the Excel method of accomplishing what this extension does, so we definitely look forward to it later this year!
