### ISSUE TITLE
Cannot create the bundle (vsix file)

### ISSUE THREAD

**Issue by saeid64** [cschleiden/vsts-quick-decompose#7]
Running _**npm run publish:release**_ throwing bunch of errors, this is the npm log:

0 info it worked if it ends with ok
1 verbose cli [ 'C:\Program Files\nodejs\node.exe',
1 verbose cli   'C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'publish:release' ]
2 info using npm@2.15.5
3 info using node@v4.4.5
4 verbose run-script [ 'prepublish:release',
4 verbose run-script   'publish:release',
4 verbose run-script   'postpublish:release' ]
5 info prepublish:release @
6 info publish:release @
7 verbose unsafe-perm in lifecycle true
8 info @ Failed to exec publish:release script
9 verbose stack Error: @ publish:release: `npm run build:release && node ./scripts/publishRelease`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:217:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:827:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid @
11 verbose cwd C:\vsts-quick-decompose
12 error Windows_NT 6.3.9600
13 error argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "run" "publish:release"
14 error node v4.4.5
15 error npm  v2.15.5
16 error code ELIFECYCLE
17 error @ publish:release: `npm run build:release && node ./scripts/publishRelease`
17 error Exit status 1
18 error Failed at the @ publish:release script 'npm run build:release && node ./scripts/publishRelease'.
18 error This is most likely a problem with the  package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     npm run build:release && node ./scripts/publishRelease
18 error You can get information on how to open an issue for this project with:
18 error     npm bugs
18 error Or if that isn't available, you can get their info via:
18 error
18 error     npm owner ls
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

If is possible can you compile into a bundle and share the vsix bundle too.

Thanks

**Comment by cschleiden** [comment]
If you only want to create the release .vsix, just add "return;" here: 
https://github.com/cschleiden/vsts-quick-decompose/blob/master/scripts/publishRelease.js#L19

I always publish the release version to the marketplace, so I didn't add individual steps there.
