### ISSUE TITLE
click "decompose work items" but nothing happens

### ISSUE THREAD

**Issue by mnbf9rca** [cschleiden/vsts-quick-decompose#8]
installed on our visualstudio.com instance, but it doesnt seem to work.

**Comment by cschleiden** [comment]
@mnbf9rca Did you try it from the backlog or from a query result? And what browser did you use?

**Comment by mnbf9rca** [comment]
from the backlog. Using Chrome. Tried from the "old" and "new" interfaces but makes no difference.

**Comment by cschleiden** [comment]
Do you get any error on the console? I cannot reproduce, unfortunately.

**Comment by mnbf9rca** [comment]
seems to be working now.... sorry for not replying.
